### ISSUE TITLE
The webview does not close after 3DSecure

### ISSUE THREAD

**Issue by Dukmasta** [paymentwall/paymentwall-ios-sdk#10]
According to your API, the webview supposed to close itself after 3D secure. 

> After 3D secure, Paymentwall backend will report the 3DS result to your server, now you can make the charge again and print the result on the webView, the webView will catch the result JSON and close the webView:
>              - {"success":1} will mark the result as success without asking to store user card.
>              - Charge object JSON will mark the result as success and ask to store user card.
>              - {"error": "error_message"} will mark the result as failed with the error message
> 

It prints "{success:1}" but the webiew doesn't close itself. I have the following merchant processing case:

```
case .merchantProcessing:
            /**
             
             Process the one-time token in your backend asynchronously
             After finish:
             - Success without asking to store card:
             brick.handleBackendChargeResult(true, chargeObject: nil, secureURL: nil, errorMessage: nil)
             - Success with asking to store card:
             brick.handleBackendChargeResult(true, chargeObject: chargedObjectDict, secureURL: nil, errorMessage: nil)
             - Error:
             brick.handleBackendChargeResult(false, chargeObject: nil, secureURL: nil, errorMessage: "some error")
             - 3D secure:
             brick.handleBackendChargeResult(false, chargeObject: nil, secureURL: url, errorMessage: nil)
             
             >After 3D secure, Paymentwall backend will report the 3DS result to your server, now you can make the charge again and print the result on the webView, the webView will catch the result JSON and close the webView:
             - {"success":1} will mark the result as success without asking to store user card.
             - Charge object JSON will mark the result as success and ask to store user card.
             - {"error": "error_message"} will mark the result as failed with the error message
             
             */
            let token = response.token?.token
            let fingerprint = (response.token?.fingerprint == nil) ? "" : response.token?.fingerprint
            let amount = String(format: "%d", `(self.data?.price)!` * Int(self.quantityTextField.text!)!)
            let currency = self.data?.currencyType
            let email = response.token?.email
            let description = self.data?.ticketName
          
            let params = [
                "uniqueId" : JoinUserInfo.getInstance.uniqueId,
                "couponId" : self.couponId!,
                "quantity" : self.quantityTextField.text!,
                "token" : token!,
                "fingerprint" : fingerprint!,
                "amount" : amount,
                "currency" : currency!,
                "email" : email!,
                "description": description!
                
            ] as [String : Any]
            
            do{
                let jsonParams = try JSONSerialization.data(withJSONObject: params, options: [])
                var request = URLRequest(url: URL(string: RestApi.purchase)!)
                request.setValue("application/json", forHTTPHeaderField: "Content-Type")
                request.httpMethod = "POST"
                request.httpBody = jsonParams
                
                URLSession.shared.dataTask(with: request){(data, res, error) in
                    if data == nil {
                        return
                    }
                    
                    do{
                        let json = try JSONSerialization.jsonObject(with: data!, options: []) as! [String:Any]
                        let result = Mapper<Message>().map(JSON: json)
                                   
                        self.message = (result?.message)!
                        
                        DispatchQueue.main.async {
                            if response.paymentType == PWPaymentTypeBrick {
                                
                                if let secureUrl = result?.redirectUrl{
                                    
                                    self.brick.handleBackendChargeResult(false, chargeObject: nil, secureURL: URL(string: secureUrl), errorMessage: nil)
                                }
                                
                
                            }
                        }
                        
                    }catch{
                        
                    }
                }.resume()
            }catch{
                
            }
```

![image](https://user-images.githubusercontent.com/6385430/44315659-75cdba80-a461-11e8-92da-82719c0e72aa.png)
![image](https://user-images.githubusercontent.com/6385430/44315674-8da53e80-a461-11e8-85fd-ccdcb9fe4f52.png)

After the {success:1} gets printed, the webview doesn't close itself. What am I doing wrong?
Please help

**Comment by Dukmasta** [comment]
```
exports.paymentWall3DSecure = function (req, res) {
    var brickToken = req.query.brick_token;
    var brickFingerprint = req.query.brick_fingerprint;
    var email = req.query.email;
    var description = req.query.description;
    var currency = req.query.currency;
    var amount = req.query.amount;
    var couponId = req.query.couponId;
    var uniqueId = req.query.uniqueId;
    var quantity = req.query.quantity;

    logger.info('PAYMENT_3D_SECURE', brickToken, brickFingerprint, email, description, currency, amount, quantity, couponId, uniqueId);

    var couponCollection = db.collection('COUPON');
    var purchasedFastTrackCollection = db.collection('PURCHASED_FAST_TRACK');
    var notificationCountCollection = db.collection('NOTIFICATION_COUNT')
    var custom = {
        secure: 1
    };

    var parameters = req.body;
    if (parameters.brick_charge_id && parameters.brick_secure_token){
        custom.charge_id = parameters.brick_charge_id;
        custom.secure_token = parameters.brick_secure_token;
    }

    var charge = new Paymentwall.Charge(amount, currency, description, email, brickFingerprint, brickToken, custom);
    charge.createCharge(function (brick_response) {
        if(brick_response.isSuccessful()){
            if(brick_response.isCaptured()){
                var charge_id = brick_response.getChargeId();
              
                //handle capture
            } else if(brick_response.isUnderReview()){
                
              //handle under review
            } else {
                

                //handle 3D secure
            }

            
        } else{
            var error_code = brick_response.getErrorCode();         //handle error
            var error_details = brick_response.getErrorDetails();

     

        };

        brick_response.getFullResponse();                      // get full response content in String format
        brick_response.getFullResponse('JSON');                // get full response content in JSON format

        res.json({success:1})
```

Above is how I am handling 3D secure. I response with "{success:1}", and still no luck

**Comment by TienVu-PW** [comment]
@Dukmasta It should be `{"success":1}` to be a valid JSON message. It should have the double quote for the key.

**Comment by Dukmasta** [comment]
@TienVu-PW 
`res.json({"success":1})`
Still doesn't work

it just prints {"success":1} and doesn't close....
 
![image](https://user-images.githubusercontent.com/6385430/44319870-8558fd80-a479-11e8-83c5-1292390da684.png)

**Comment by Dukmasta** [comment]
@TienVu-PW Any updates on this???
Maybe a bug in the SDK??

**Comment by TienVu-PW** [comment]
@Dukmasta We have a check it again and realize that we are only handle the response that's wrapped in a html content, not raw JSON, we will add handler for more kinds of response and update it ASAP. Please check back later and update the SDK.

**Comment by Dukmasta** [comment]
@TienVu-PW Any workaround in the meantime?

**Comment by Dukmasta** [comment]
@TienVu-PW It's been a week since I encounter this. Please help me out. Please... I need to launch my app ASAP

**Comment by TienVu-PW** [comment]
@Dukmasta We are sorry to hear that, we will update new version in 30 mins - 1 hour then you can update and try again, the workaround for now is that you can display your own webView for the 3DS and make direct communication between your backend and app.

**Comment by Dukmasta** [comment]
@TienVu-PW Thanks
Please let me know when you update it.

**Comment by TienVu-PW** [comment]
@Dukmasta We have pushed new update, please update it with `pod update`, there's also a small change on declaring `PWPaymentObject`, now it will be declaring with initialize method so please make sure you cover that too, thanks.

**Comment by TienVu-PW** [comment]
@Dukmasta Can you try again with an error response eg.`{"error": "some error"}` to see if it read?

**Comment by Dukmasta** [comment]
@TienVu-PW 
`res.json({"error": "this is a webview test error"})`

I respond with above and it print the error as follows:

![image](https://user-images.githubusercontent.com/6385430/44333417-afc2af00-a4a9-11e8-99e1-dcd7475770b3.png)

**Comment by TienVu-PW** [comment]
The best guess why this is not working is that there're extra HTML/Javascript content that interfere with the `JSONSerialization` in the app, please try to call the 3DS URL on PC's browser, enter the credential and make sure the redirected page source just contains the JSON message.

**Comment by Dukmasta** [comment]
@TienVu-PW 
Ok, I looked through the returned page source and it contains
`<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"success":1}</pre></body></html>`

Do you think this is the problem?

**Comment by TienVu-PW** [comment]
Yes, the body should only be contains the JSON without any styling.

**Comment by Dukmasta** [comment]
@TienVu-PW I have used all methods but nothing is working. Do you have any idea how to remove styling from the response?

**Comment by Dukmasta** [comment]
@TienVu-PW Finally figured it out. Ended up using http://expressjs.com/en/guide/using-template-engines.html

**Comment by TienVu-PW** [comment]
Hi @Dukmasta , glads to hear you solved it, we are discussing the impact of stripping HTML tags on detecting the web content and will considering add this feature on the future.

**Comment by Dukmasta** [comment]
@TienVu-PW Thank you for your help 👍
