### ISSUE TITLE
How to display an error occurred during an initial charge

### ISSUE THREAD

**Issue by Dukmasta** [paymentwall/paymentwall-ios-sdk#11]
During an initial charge i.e. before 3D Secure, I get an "Charge amount is too high" error. When this occur, I respond with a JSON error message to the client. However, the loading image continues until it is timed out.

How do I properly display error messages from my server?

**Comment by TienVu-PW** [comment]
Hi @Dukmasta , you should parse the JSON within your app to get the error message string, then call this to show the error:
`self.brick.handleBackendChargeResult(false, chargeObject: nil, secureURL: nil, errorMessage: someErrorString)`

**Comment by Dukmasta** [comment]
@TienVu-PW Aha! I see. Thanks!
