### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rakeshkathoju** [paymentwall/paymentwall-ios-sdk#3]
Hi Tien Nhat Vu, app is crashing when i am running from testflight build in iOS 10.3.3 . i am using cocopods with swift

**Comment by michaelpw** [comment]
Hi,


Can you try debugging what the error is from? Our SDK shouldn't affect the build on Testflight.

Thanks,
Michael

**Comment by TienVu-PW** [comment]
Hi @rakeshkathoju, I have tested it with Testflight and it work okay, please make sure you are not missing some requirement in `info.plist`:

- Add this if you are using native payment plugins:
```
        <key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

- Add this if you are using native payment plugins or card scanner plugin:
```
<key>NSCameraUsageDescription</key>
<string>To scan credit card</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>To get image</string>
```
- And some `LSApplicationQueriesSchemes` as mentioned in the plugins docs
