### ISSUE TITLE
Secret key in iOS app?

### ISSUE THREAD

**Issue by adolfogc** [paymentwall/paymentwall-ios-sdk#5]
From your [README](https://github.com/paymentwall/paymentwall-ios-sdk/blob/master/Core%20SDK/README.md):

```
PWCoreSDK.sharedInstance().setupPaymentwall(withProjectKey: "YOUR PUBLIC KEY", secretKey: "YOUR SECRET KEY", requestTimeout: 30, clearPaymentMethodsAfterFinish: false)
```

In which cases is using the `secretKey` in your iOS app recommended?

**Comment by michaelpw** [comment]
Hi,

If you integrate Brick Native only, you don't have to specify secret key for this initiation.

This is recommended in case you want to integrate PWLocal and other payment options plugins.

Best Regards,
Michael
