### ISSUE TITLE
Customized UI

### ISSUE THREAD

**Issue by adolfogc** [paymentwall/paymentwall-ios-sdk#6]
I need to also customize this element:

<img src="https://user-images.githubusercontent.com/1250775/35485596-9cec60a6-0427-11e8-885a-0fc299d8d64b.jpeg"  width="50%" height="50%" />

Is that possible?

**Comment by michaelpw** [comment]
Hi,

This is not possible to customize at the moment. We will put this development into our road map.

Thank you,
Michael

**Comment by TienVu-PW** [comment]
@adolfogc This have been added in v3.0.0, please update the SDK to customize this.
