### ISSUE TITLE
Customize Buttons

### ISSUE THREAD

**Issue by TTHoriuchi** [paymentwall/paymentwall-ios-sdk#7]
How can I customize scan button with camera icon?
When I set  backgroundColor commonButtonConfig as bellow, the camera icons was disappeared.

_let button = UIButton(type: UIButtonType.custom)
        custom.commonButtonConfig = button
        custom.commonButtonConfig.backgroundColor = UIColor(red: r, green: g, blue: b, alpha: 1.0)
        custom.commonButtonConfig.tintColor = UIColor(red: r, green: g, blue: b, alpha: 1.0)_

![img_0160](https://user-images.githubusercontent.com/39119409/39806499-0dcc937c-53b5-11e8-9323-9043730fa688.PNG)

**Comment by TienVu-PW** [comment]
Dear @TTHoriuchi ,
Thanks for inform us about the bug. We have updated the SDK to fix this issue, now the button will properly show the image, and background will always be `clearColor`, please update it to see if it's fixed.
Thanks,
Kyle
