### ISSUE TITLE
Customize e-mail input-field

### ISSUE THREAD

**Issue by TTHoriuchi** [paymentwall/paymentwall-ios-sdk#8]
How can I make e-mail input-field optional or invisible?
My server will send e-mail of the receipt to users when pingback is called, so I guess that the field is not necessary.
![input_email](https://user-images.githubusercontent.com/39119409/41521938-18b87e58-730f-11e8-98bd-4bdb7776ac35.jpeg)

**Comment by TienVu-PW** [comment]
Hi @TTHoriuchi,

It's not optional right now due to the payment requirements, we will consult with the payment team for next version to confirm if this field can be made optional or not.

Thanks,
Kyle.

**Comment by TTHoriuchi** [comment]
I'm glad that you are considering our proposal.
Thanks!
