### ISSUE TITLE
How to add custom parameters

### ISSUE THREAD

**Issue by aishuidedabai** [paymentwall/paymentwall-ios-sdk#9]
Such as orderID why 2.0 version can be added, 3.0 does not have this parameter

**Comment by TienVu-PW** [comment]
Hi @aishuidedabai,
Can you inform me which payment option you are having trouble with the `orderID` param?

**Comment by aishuidedabai** [comment]
Hi  When I was using version 3.0, I found that there are some differences between 2.0 and I want to customize a parameter orderID, need to use a dictionary to send, I found a method in the PWPaymentObject-(NSDictionary * _Nonnull) toDict; this method, But I don't know how to use it, can it pass custom parameters to the server, if not, then how should I pass the orderID to the server?

**Comment by aishuidedabai** [comment]
![2018-06-21 4 49 12](https://user-images.githubusercontent.com/18343966/41708446-359022f4-7573-11e8-850c-ef6c270c611a.png)
![da9bc4d2-b868-4d96-bb4e-683ae3c6c2c4](https://user-images.githubusercontent.com/18343966/41708449-35ce6b5e-7573-11e8-8a75-7c35c12cb343.png)

**Comment by TienVu-PW** [comment]
I think you are talking about the changes of our Widget payment option.
The widget's custom settings in v3.0 have been moved to it's own class `PWOptionWidget` as `extraParams`, so you can include it like this:

```
let widget = PWOptionWidget(type: .digitalGoodsFlexible, extraParams: ["widget":"m2_1",
                                                                       "ag_type":"fixed"])
```

The `PaymentObject` class now only include params related to payment info.

Please try to see if this resolve your problem,
Kyle

**Comment by aishuidedabai** [comment]
The implication is that I can add other parameters here, such as
let widget = PWOptionWidget(type: .digitalGoodsFlexible, extraParams: ["widget":"m2_1",
                                                                       "ag_type":"fixed"]，"orderID":"123"，"user":"abc"，"time":"1232313132") @TienVu-PW

**Comment by TienVu-PW** [comment]
Yes, you can, it have the same function as the `pwLocalParams` in v2.0, just include all the params you need in the dictionary and pass to `extraParams`

**Comment by aishuidedabai** [comment]
Only set to md5 encryption, is this writing correct because I always fail to pay。
   PWCoreSDK.sharedInstance().setGlobalSign(PWSignatureType(rawValue: 2)!) //md5
 @TienVu-PW

**Comment by TienVu-PW** [comment]
It's correct, but you can just write `PWCoreSDK.sharedInstance().setGlobalSign(.MD5)`
By fail to pay, do you meant the Widget display error?

**Comment by aishuidedabai** [comment]
![2018-06-21 5 36 30](https://user-images.githubusercontent.com/18343966/41711021-abf88232-7579-11e8-8c0f-15607b08d7ec.png)

**Comment by TienVu-PW** [comment]
Please try remove `"widget":"m2_1"` from the custom setting and try again.

**Comment by aishuidedabai** [comment]
![2018-06-21 5 44 07](https://user-images.githubusercontent.com/18343966/41711519-d8ab51b4-757a-11e8-8f3d-5ba702f0dcd2.png)
![image 2018-06-21 17 42 57](https://user-images.githubusercontent.com/18343966/41711520-d8ecdb66-757a-11e8-9f66-82ae4760aa40.jpg)

I have set up support for UnionPay, but it still doesn't show up. Is this normal? @TienVu-PW

**Comment by TienVu-PW** [comment]
@aishuidedabai 
Can you provide screenshot of Unionpay's countries setting?

**Comment by aishuidedabai** [comment]
In the code, I did not set up UnionPay information. I also used the simulator to run it. I wanted to set it on the interface but I did not support it.
![image 2018-06-21 18 03 26](https://user-images.githubusercontent.com/18343966/41712639-9dda7fb2-757d-11e8-9879-080ec4ecb662.jpg)
![image 2018-06-21 18 04 51](https://user-images.githubusercontent.com/18343966/41712641-9e1818d6-757d-11e8-92e4-fd244fb538e5.jpg)

**Comment by masonpham** [comment]
Hi @aishuidedabai, 
Could you provide me Project Id, i will check this issue for you

**Comment by aishuidedabai** [comment]
Will sandbox mode, the user does not need real payment, but I did not see the way to open the sandbox in the demo. What code do I need to add to activate in the front end? @TienVu-PW

**Comment by TienVu-PW** [comment]
@aishuidedabai There's no code to activate in frontend, just need to change your project key to test key in your setup code to change to sandbox mode, but It would be better to provide the project key for @masonpham to help you

**Comment by aishuidedabai** [comment]
My Wechat ID: txb3210.   Telegram：17621947133 @masonpham

**Comment by aishuidedabai** [comment]
Will widgetFlex.widget = "m2_1"  What does widgetFlex.ag_type = "fixed" mean? 
Is UnionPay card payment only in PWWidgetDigitalGoodsFlexible? @TienVu-PW

**Comment by TienVu-PW** [comment]
Please check [our docs](https://www.paymentwall.com/en/documentation/Digital-Goods-API/710#default_widget_call_parameters) to see what params you can use to call widget

**Comment by aishuidedabai** [comment]
Can I open the test mode to use Alipay?
